# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-hello-worlds"
BBFILE_PATTERN_meta-hello-worlds = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-hello-worlds = "6"

LAYERDEPENDS_meta-hello-worlds = "core"
LAYERSERIES_COMPAT_meta-hello-worlds = "wrynose"
