SUMMARY = "Small Rust hello application"
DESCRIPTION = "Builds a Rust application and demonstrates locked Cargo dependencies in a Yocto recipe."
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"

inherit cargo
inherit cargo-update-recipe-crates

SRC_URI = " \
    file://Cargo.toml \
    file://Cargo.lock \
    file://src/main.rs \
"

# AUTOGENERATED from Cargo.lock. After changing Rust dependencies, run:
#
#     bitbake -c update_crates hello-rust
#
require ${BPN}-crates.inc

S = "${UNPACKDIR}"

do_install() {
    install -d ${D}${bindir}
    install -m 0755 ${B}/target/${CARGO_TARGET_SUBDIR}/hello-rust ${D}${bindir}/hello-rust
}
